--- 
- name: 'Print list of fruits'
  hosts: localhost
  vars:
    fruits:
      - Apple
      - Banana
      - Grapes
      - Oranges
  tasks:
    - command: 'echo "{{ item }}"'
      with_items: '{{ fruits }}'